### ISSUE TITLE
(Question) Send attachments?

### ISSUE THREAD

**Issue by pandalec** [thegeeklab/drone-matrix#78]
Hey!
Would it be possible to send attachments via Matrix? Like adding a pdf, html document with test results or whatever?
BR

**Comment by xoxys** [comment]
Hello, I guess technically possible, but not yet implemented.

**Comment by xoxys** [comment]
Have taken a short look, and I'm not sure if I would like to go this way. It's not possible to send text and files as a single message. That means sending the normal message generated from the template `Build xy has succeeded`  and sending a file artifact needs to be done by two separate messages (or even more if multiple files should be attached). 

While multiple CI Pipelines can finish at the same time, messages from multiple pipelines would be sent in mixed order, and it's no longer possible to identify what attachment is related to what CI run. Due to this reason, I would suggest uploading build artifacts to something else, e.g. S3, GH Pull Request comments, FTP etc. and add a URL to the matrix message template.

**Comment by pandalec** [comment]
Thank you very much, sounds like good workaround. I'll give it a try :)
